sudo: required
language: c
services:
    - docker

before_install:
- docker pull zhuangjw/docker_gc

script:
- docker run -it --rm -v $(pwd):/root/workdir zhuangjw/docker_gc /bin/bash -c "cd /root/workdir && make realclean && make -j8 MET=geosfp GRID=4x5 NO_REDUCED=y CHEM=Standard TIMERS=1 BPCH_DIAG=y"
- docker run -it --rm -v $(pwd):/root/workdir zhuangjw/docker_gc /bin/bash -c "cd /root/workdir && make realclean && make -j8 MET=geosfp GRID=4x5 CHEM=Tropchem TIMERS=1 BPCH_DIAG=y"
- docker run -it --rm -v $(pwd):/root/workdir zhuangjw/docker_gc /bin/bash -c "cd /root/workdir && make realclean && make -j8 MET=geosfp GRID=4x5 CHEM=SOA_SVPOA TIMERS=1 BPCH_DIAG=y"
- docker run -it --rm -v $(pwd):/root/workdir zhuangjw/docker_gc /bin/bash -c "cd /root/workdir && make realclean && make -j8 MET=geosfp GRID=025x03125 NEST=ch CHEM=Tropchem TIMERS=1 BPCH_DIAG=y"
- docker run -it --rm -v $(pwd):/root/workdir zhuangjw/docker_gc /bin/bash -c "cd /root/workdir && make realclean && make -j8 MET=geosfp GRID=025x03125 NEST=na CHEM=Tropchem TIMERS=1 BPCH_DIAG=y"
- docker run -it --rm -v $(pwd):/root/workdir zhuangjw/docker_gc /bin/bash -c "cd /root/workdir && make realclean && make -j8 MET=geosfp GRID=025x03125 NEST=eu CHEM=Tropchem TIMERS=1 BPCH_DIAG=y"
- docker run -it --rm -v $(pwd):/root/workdir zhuangjw/docker_gc /bin/bash -c "cd /root/workdir && make realclean && make -j8 MET=merra2 GRID=05x0625 NEST=as CHEM=Tropchem TIMERS=1 BPCH_DIAG=y"
- docker run -it --rm -v $(pwd):/root/workdir zhuangjw/docker_gc /bin/bash -c "cd /root/workdir && make realclean && make -j8 MET=merra2 GRID=05x0625 NEST=na CHEM=Tropchem TIMERS=1 BPCH_DIAG=y"
- docker run -it --rm -v $(pwd):/root/workdir zhuangjw/docker_gc /bin/bash -c "cd /root/workdir && make realclean && make -j8 MET=merra2 GRID=05x0625 NEST=eu CHEM=Tropchem TIMERS=1 BPCH_DIAG=y"

notifications:
    slack: gcst:7j7EWzrMDfTbRlG2yYRAbffc